version: '3'

services:      
  frontend:
    container_name: client
    build: 
      context: .
      dockerfile: Dockerfile.client 
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/client
    working_dir: /client/
    command: npm run dev